import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAuth } from "../context/auth.js";
import styled from "@emotion/styled";
import dynamic from "next/dynamic";
import Query from "../components/Query";
import SUMMONER_QUERY from "../queries/summoner/summoner";

const ThemeToggle = dynamic(() => import("../components/ThemeToggle"), {
  ssr: false,
});

const Summoner = styled.div`
  flex-direction: column;

  p {
    padding: 0;
    margin: 0;
    line-height: 1.5;
  }

  img {
    margin-bottom: 10px;
    border-radius: 50px 50px;
  }
`;

const Container = styled.div`
  display: flex;
  justify-content: center;
  padding-top: 35vh;
`;

const Stats = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export default function Home() {
  const { logout } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {/* <ThemeToggle /> */}
        <main className={styles.main}>
          {/* <button onClick={() => logout()}>Log Out</button> */}

          <Query query={SUMMONER_QUERY} summoner="TwistedPot">
            {({ data: { SummonerInfo } }) => {
              return (
                <div>
                  <Summoner className={styles.grid}>
                    <img
                      src={`http://ddragon.leagueoflegends.com/cdn/11.15.1/img/profileicon/${SummonerInfo.profileIconId}.png`}
                      alt="Image"
                      height="100"
                      width="100"
                    />

                    <p>{SummonerInfo.name}</p>
                    <p>Level: {SummonerInfo.summonerLevel}</p>
                  </Summoner>
                  <div className={styles.grid}>
                    {SummonerInfo.games.map((game) => {
                      return (
                        <div className={styles.card} key={game.gameCreation}>
                          <Stats>
                            <div
                              style={{
                                display: "flex",
                                flexDirection: "row",
                                justifyContent: "center",
                                alignItems: "center",
                              }}
                            >
                              <img
                                src={`http://ddragon.leagueoflegends.com/cdn/11.15.1/img/champion/${game.championName}.png`}
                                alt="Image"
                                height="50"
                                width="50"
                                style={{
                                  borderRadius: "50px 50px",
                                }}
                              />
                              <p
                                style={{
                                  paddingLeft: "25px",
                                }}
                              >
                                {game.championName}
                              </p>
                            </div>
                            <div
                              style={{
                                display: "flex",
                                flexDirection: "row",
                                justifyContent: "center",
                                alignItems: "center",
                                padding: "10px 0px",
                              }}
                            >
                              <img
                                src={`http://ddragon.leagueoflegends.com/cdn/5.5.1/img/ui/score.png`}
                                alt="Image"
                                height="25"
                                width="25"
                              />
                              <p>
                                {game.kills +
                                  "/" +
                                  game.deaths +
                                  "/" +
                                  game.assists}
                              </p>
                            </div>
                            <div
                              style={{
                                display: "flex",
                                flexDirection: "column",
                                width: "100%",
                              }}
                            >
                              <p>Champion Level: {game.champLevel}</p>
                              <p>Mode: {game.gameMode}</p>
                              <p>
                                Duration:{" "}
                                {Math.round(game.gameDuration / 1000 / 60)}{" "}
                                minutes.
                              </p>
                              <p>Result: {game.win ? "Win" : "Lose"}</p>
                            </div>
                          </Stats>
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            }}
          </Query>
        </main>
      </Container>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
